django/axis/urls.py
from django.urls import path

from axis import views

app_name = 'axis'
urlpatterns = [
    path("list/", views.AxleListView.as_view(), name="list"),
    path("create/", views.AxleCreateView.as_view(), name="create"),
    path("update/<uuid:pk>", views.AxleUpdateView.as_view(), name="update"),
]

django/biopark/urls.py
"""biopark URL Configuration."""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from biopark import views


urlpatterns = [
    path("", views.InitialView.as_view(), name='initial'),
    path("home/", views.HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/", include("biopark.api_urls")),
    path("eixos/", include("axis.urls")),
    path("avaliacoes/", include("exams.urls")),
    path("eixos/listar/", views.EixosList.as_view()),

    path("perguntas/listagem/", views.PerguntasList.as_view(), name='ListagemPerguntas'),
    path("perguntas/cadastro/", views.PerguntasCad.as_view(), name='CadastroPerguntas'),
    path("eixos/listagem/", views.EixosList.as_view(), name='ListagemEixos'),
    path("eixos/cadastro/", views.EixosCad.as_view(), name='CadastroEixos'),
    path("instituições/", views.Instituicao.as_view(), name='instituicao'),
    path("relatórios/", views.Relatorios.as_view(), name='relatorios'),
    path("importar/alunos/", views.ImportarAlunos.as_view(), name='alunos'),
    path("relatórios/professores/", views.ImportarProfessores.as_view(), name='professores'),
    path("perguntas/", include('questions.urls')),
    path("perguntas/listagem/", views.PerguntasList.as_view(), name='ListagemPerguntas'),
    path("perguntas/cadastro/", views.PerguntasCad.as_view(), name='CadastroPerguntas'),
    path("eixos/listagem/", views.EixosList.as_view(), name='ListagemEixos'),
    path("eixos/cadastro/", views.EixosCad.as_view(), name='CadastroEixos'),
    path("instituições/", views.Instituicao.as_view(), name='instituicao'),
    path("relatórios/", views.Relatorios.as_view(), name='relatorios'),
    path("importar/alunos/", views.ImportarAlunos.as_view(), name='alunos'),
    path("relatórios/professores/", views.ImportarProfessores.as_view(), name='professores')
]


handler400 = views.Handler400View.as_view()
handler403 = views.Handler403View.as_view()
handler404 = views.Handler404View.as_view()
handler500 = views.Handler500View.as_view()


if settings.DEBUG:
    # Getting media files for debug environment.
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

    # Getting django-debug-toolbar assets.
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns

django/biopark/views.py
"""Biopark views for Biopark Search project."""
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from users.models import User


class InitialView(RedirectView):
    """
    Home page
    """
    def get_redirect_url(self, *args, **kwargs):
        user = User.objects.filter(pk=self.request.user.pk).first()

        if not user:
            return reverse_lazy("login")
        return reverse_lazy("home")


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'prepages/home/home.html'


class PerguntasList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/perguntas/ListagemPerguntas.html'


class PerguntasCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/perguntas/CadastroPerguntas.html'


class AvaliacaoList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/avaliacao/ListagemAvaliacao.html'


class AvaliacaoCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/avaliacao/CriarAvaliacao.html'


class EixosList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/eixos/ListagemEixos.html'


class EixosCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/eixos/CadastroEixos.html'


class Instituicao(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/instituicao/instituicao.html'


class Relatorios(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/relatorios/relatorios.html'


class ImportarAlunos(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/importar/alunos.html'


class ImportarProfessores(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/importar/professores.html'


class Handler400View(TemplateView):
    """
    Handler 400 view.
    """
    template_name = 'handler/400.html'


class Handler404View(TemplateView):
    """
    Handler 404 view.
    """
    template_name = 'handler/404.html'


class Handler500View(TemplateView):
    """
    Handler 500 view.
    """
    template_name = 'handler/500.html'


class Handler403View(TemplateView):
    """
    Handler 403 view.
    """
    template_name = 'handler/403.html'

django/biopark/templates/prepages/eixos/editor/editoreixo.html
{% extends 'layout/_default.html' %}
{% load static crispy_forms_tags widget_tweaks %}

{% block toolbar %}
  <div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
    <div id="kt_app_toolbar_container" class="app-container container-xxl d-flex flex-stack">
      <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
        <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">Eixos</h1>
        <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
          <li class="breadcrumb-item text-muted">
            <a href="{% url 'axis:list' %}" class="text-muted text-hover-primary">Listagem</a>
          </li>
          <li class="breadcrumb-item">
            <span class="bullet bg-gray-400 w-5px h-2px"></span>
          </li>
          <li class="breadcrumb-item text-muted">Cadastro</li>
        </ul>
      </div>
      <div class="d-flex align-items-center gap-2 gap-lg-3">
        <a href="http://localhost:8000/eixos/listar/" class="btn btn-sm fw-bold btn-primary">Voltar</a>
      </div>
    </div>
  </div>
{% endblock toolbar %}

{% block content %}
<div id="kt_app_content" class="app-content flex-column-fluid">
  <div id="kt_app_content_container" class="app-container container-xxl">
    <form id="kt_company_editor_form" class="form" method="post" enctype="multipart/form-data" novalidate>
      {% csrf_token %}
      <!--begin::Input group-->
    <div class="input-group mb-5">
      <span class="input-group-text" id="basic-addon1">Nome do eixo</span>
      <input type="text" class="form-control" placeholder="Nome" aria-label="Nome" aria-describedby="basic-addon1"/>
    </div>
    
    <!--end::Input group-->
    
<!--begin::solid autosize textarea-->
<div>
  <label for="" class="form-label">Descrição</label>
  <textarea placeholder="Descrição" class="form-control mb-5" data-kt-autosize="true"></textarea>
</div>
<!--end::solid autosize textarea-->

    </form>
    <div class="border-start 10 d-flex align-items-center gap-2 gap-lg-3">
      <button type="button" id="AdicionarCadastroEixo" class="btn btn-sm fw-bold btn-primary">Adicionar</button>
      <button type="button" id="CancelarCadastroEixo" class="btn btn-sm btn-danger btn-primary">Cancelar</button>
    </div>
  </div>
</div>


{% endblock content %}


{% block js-import %}
  <script src="{% static 'js/test.js' %}"></script>
{% endblock js-import %}