django/axis/urls.py
from django.urls import path

from axis import views

app_name = 'axis'
urlpatterns = [
    path("list/", views.AxleListView.as_view(), name="list"),
    path("create/", views.AxleCreateView.as_view(), name="create"),
    path("update/<uuid:pk>", views.AxleUpdateView.as_view(), name="update"),
]

django/biopark/urls.py
"""biopark URL Configuration."""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from biopark import views


urlpatterns = [
    path("", views.InitialView.as_view(), name='initial'),
    path("home/", views.HomeView.as_view(), name='home'),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/", include("biopark.api_urls")),
    path("eixos/", include("axis.urls")),
    path("avaliacoes/", include("exams.urls")),
    path("eixos/listar/", views.EixosList.as_view()),

    path("perguntas/listagem/", views.PerguntasList.as_view(), name='ListagemPerguntas'),
    path("perguntas/cadastro/", views.PerguntasCad.as_view(), name='CadastroPerguntas'),
    path("eixos/listagem/", views.EixosList.as_view(), name='ListagemEixos'),
    path("eixos/cadastro/", views.EixosCad.as_view(), name='CadastroEixos'),
    path("instituições/", views.Instituicao.as_view(), name='instituicao'),
    path("relatórios/", views.Relatorios.as_view(), name='relatorios'),
    path("importar/alunos/", views.ImportarAlunos.as_view(), name='alunos'),
    path("relatórios/professores/", views.ImportarProfessores.as_view(), name='professores'),
    path("perguntas/", include('questions.urls')),
    path("perguntas/listagem/", views.PerguntasList.as_view(), name='ListagemPerguntas'),
    path("perguntas/cadastro/", views.PerguntasCad.as_view(), name='CadastroPerguntas'),
    path("eixos/listagem/", views.EixosList.as_view(), name='ListagemEixos'),
    path("eixos/cadastro/", views.EixosCad.as_view(), name='CadastroEixos'),
    path("instituições/", views.Instituicao.as_view(), name='instituicao'),
    path("relatórios/", views.Relatorios.as_view(), name='relatorios'),
    path("importar/alunos/", views.ImportarAlunos.as_view(), name='alunos'),
    path("relatórios/professores/", views.ImportarProfessores.as_view(), name='professores')
]


handler400 = views.Handler400View.as_view()
handler403 = views.Handler403View.as_view()
handler404 = views.Handler404View.as_view()
handler500 = views.Handler500View.as_view()


if settings.DEBUG:
    # Getting media files for debug environment.
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

    # Getting django-debug-toolbar assets.
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns

django/exams/urls.py
from django.urls import path

from exams import views


app_name = 'exams'
urlpatterns = [
    path("list/", views.ExamListView.as_view(), name="list"),
    path("create/", views.ExamCreateView.as_view(), name="create"),
    path("update/<uuid:pk>", views.ExamUpdateView.as_view(), name="update")
]

django/biopark/views.py
"""Biopark views for Biopark Search project."""
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from users.models import User


class InitialView(RedirectView):
    """
    Home page
    """
    def get_redirect_url(self, *args, **kwargs):
        user = User.objects.filter(pk=self.request.user.pk).first()

        if not user:
            return reverse_lazy("login")
        return reverse_lazy("home")


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'prepages/home/home.html'


class PerguntasList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/perguntas/ListagemPerguntas.html'


class PerguntasCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/perguntas/CadastroPerguntas.html'


class AvaliacaoList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/avaliacao/ListagemAvaliacao.html'


class AvaliacaoCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/avaliacao/CriarAvaliacao.html'


class EixosList(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/eixos/ListagemEixos.html'


class EixosCad(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/eixos/CadastroEixos.html'


class Instituicao(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/instituicao/instituicao.html'


class Relatorios(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/relatorios/relatorios.html'


class ImportarAlunos(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/importar/alunos.html'


class ImportarProfessores(LoginRequiredMixin, TemplateView):
    """
    TemplateView de exemplo
    """
    login_url = reverse_lazy('login')
    template_name = 'prepages/importar/professores.html'


class Handler400View(TemplateView):
    """
    Handler 400 view.
    """
    template_name = 'handler/400.html'


class Handler404View(TemplateView):
    """
    Handler 404 view.
    """
    template_name = 'handler/404.html'


class Handler500View(TemplateView):
    """
    Handler 500 view.
    """
    template_name = 'handler/500.html'


class Handler403View(TemplateView):
    """
    Handler 403 view.
    """
    template_name = 'handler/403.html'

django/biopark/templates/layout/partials/header/_menu/_menu.html
<!--begin::Menu wrapper-->
<div class="app-header-menu app-header-mobile-drawer align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="app-header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="225px" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_app_header_menu_toggle" data-kt-swapper="true" data-kt-swapper-mode="{default: 'append', lg: 'prepend'}" data-kt-swapper-parent="{default: '#kt_app_body', lg: '#kt_app_header_wrapper'}">
	<!--begin::Menu-->
	<div class="menu menu-rounded menu-column menu-lg-row my-5 my-lg-0 align-items-stretch fw-semibold px-2 px-lg-0" id="kt_app_header_menu" data-kt-menu="true">
		<div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
			<!--begin:Menu link-->
			<span class="menu-link">
				<span class="menu-title">Avaliações</span>
				<span class="menu-arrow d-lg-none"></span>
			</span>
			<!--end:Menu link-->
			<!--begin:Menu sub-->
			<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-lg-2 py-lg-4 w-lg-200px">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link--> 
					<a class="menu-link" href="{% url 'exams:list' %}"  data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/general/gen002.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Listar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'exams:create' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Criar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
			</div>
			<!--end:Menu sub-->
		</div>
		<!--end:Menu item-->
		<!--begin:Menu item-->
		<div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
			<!--begin:Menu link-->
			<span class="menu-link">
				<span class="menu-title">Perguntas</span>
				<span class="menu-arrow d-lg-none"></span>
			</span>
			<!--end:Menu link-->
			<!--begin:Menu sub-->
			<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-lg-2 py-lg-4 w-lg-200px">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'ListagemPerguntas' %}"  data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/general/gen002.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Listar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'CadastroPerguntas' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Cadastrar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
			</div>
			<!--end:Menu sub-->
		</div>
		<!--end:Menu item-->
		<!--begin:Menu item-->
		<div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
			<!--begin:Menu link-->
			<span class="menu-link">
				<span class="menu-title">Eixos</span>
				<span class="menu-arrow d-lg-none"></span>
			</span>
			<!--end:Menu link-->
			<!--begin:Menu sub-->
			<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-lg-2 py-lg-4 w-lg-200px">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'ListagemEixos' %}"  data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/general/gen002.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Listar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'CadastroEixos' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Cadastrar</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
			</div>
			<!--end:Menu sub-->
		</div>
		<!--end:Menu item-->
		<div data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
			<!--begin:Menu link-->

			<a class="menu-link" href="{% url 'instituicao' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
				{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
				<span class="menu-title">Instituições</span>
			</a>
			<!--end:Menu link-->
		</div>
		<!--begin:Menu item-->
		<div  data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-0 me-lg-2">
			<!--begin:Menu link-->
			<a class="menu-link" href="{% url 'relatorios' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
				{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
				<span class="menu-title">Relatórios</span>
			</a>
			<!--end:Menu link-->
		</div>
		<!--end:Menu item-->
		<!--begin:Menu item-->
		<div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion menu-sub-lg-down-indention me-0 me-lg-2">
			<!--begin:Menu link-->
			<span class="menu-link">
				<span class="menu-title">Importar</span>
				<span class="menu-arrow d-lg-none"></span>
			</span>
			<!--end:Menu link-->
			<!--begin:Menu sub-->
			<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown px-lg-2 py-lg-4 w-lg-200px">
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'alunos' %}"  data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/general/gen002.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Alunos</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
				<!--begin:Menu item-->
				<div class="menu-item">
					<!--begin:Menu link-->
					<a class="menu-link" href="{% url 'professores' %}" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
						{% comment %} <span class="menu-icon">{% getSvgIcon 'duotune/abstract/abs027.svg' 'svg-icon svg-icon-3' %}</span> {% endcomment %}
						<span class="menu-title">Professores</span>
					</a>
					<!--end:Menu link-->
				</div>
				<!--end:Menu item-->
			</div>
			<!--end:Menu sub-->
		</div>
		<!--end:Menu item-->
	</div>
	<!--end::Menu-->
</div>
<!--end::Menu wrapper-->